sudo: required

language: node_js
dist: trusty

node_js:
  - "stable"

services:
  - docker

env:
  - DOCKER_IMAGE=rso9/media-storage:0.1.0

script:
  - docker build -t "$DOCKER_IMAGE" .
  - docker run -d -p 8080:8080 "$DOCKER_IMAGE"

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master